language: objective-c
osx_image: xcode7.3
branches:
  only:
    - master
script:
  - xctool test -project MagicSpell.xcodeproj -scheme MagicSpellKeyboard clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

notifications:
  email: false
  slack: magicspell:v42BGKyOXS3WCDxpIsVvlkgB
